#!/bin/bash

# 🎯 Quick Guide: Connect Your Real Instagram Account

echo "=========================================="
echo "🔗 INFLUENCE CONNECT - INSTAGRAM SETUP"
echo "=========================================="
echo ""

echo "✅ STEP 1: Create Meta Developer App"
echo "--------------------------------------------"
echo "1. Go to: https://developers.facebook.com"
echo "2. Create App > Choose 'Business' type"
echo "3. Name: Influence Connect"
echo "4. Complete business info"
echo ""

echo "✅ STEP 2: Get Your Credentials"
echo "--------------------------------------------"
echo "In your app Settings > Basic:"
echo "• App ID: COPY THIS"
echo "• App Secret: COPY THIS"
echo ""
echo "In Graph API Explorer:"
echo "• Generate Access Token > COPY THIS"
echo "• Get your Business Account ID: /me query"
echo ""

echo "✅ STEP 3: Configure Webhook"
echo "--------------------------------------------"
echo "1. Go to: Settings > Messenger"
echo "2. Under 'Webhooks':"
echo "   • Callback URL: https://influence-connect-production.up.railway.app/api/instagram/webhook"
echo "   • Verify Token: (create any string, e.g., 'your-secret-verify-token-2024')"
echo ""
echo "3. Subscribe to Fields:"
echo "   ☑️ messages"
echo "   ☑️ message_echoes"
echo "   ☑️ comments"
echo ""

echo "✅ STEP 4: Set Environment Variables"
echo "--------------------------------------------"
echo "In Railway.app > Your Project > FastAPI Service > Variables:"
echo ""
echo "Add these variables (copy from above):"
echo "  INSTAGRAM_VERIFY_TOKEN=your-secret-verify-token-2024"
echo "  INSTAGRAM_APP_SECRET=<your-app-secret>"
echo "  INSTAGRAM_ACCESS_TOKEN=<your-access-token>"
echo "  INSTAGRAM_BUSINESS_ACCOUNT_ID=<your-business-account-id>"
echo ""

echo "✅ STEP 5: Verify Webhook"
echo "--------------------------------------------"
echo "Back in Meta Developer Dashboard:"
echo "1. Click 'Test Webhook' next to your URL"
echo "2. You should see: ✅ Webhook verified"
echo "3. Check Railway logs (should show: ✅ Webhook verified with Instagram)"
echo ""

echo "✅ STEP 6: Send Real Test Message"
echo "--------------------------------------------"
echo "1. Open Instagram"
echo "2. Find your business account"
echo "3. DM your business with: 'Test message'"
echo ""
echo "Watch Railway logs:"
echo "• You should see: 📨 DM Event"
echo "• Message saved to database"
echo "• Full AI pipeline runs"
echo "• Response generated"
echo ""

echo "=========================================="
echo "🚀 NOW LIVE!"
echo "=========================================="
echo ""
echo "Endpoints ready:"
echo "  • GET /api/health - Check API status"
echo "  • GET /api/instagram/status - Check webhook"
echo "  • POST /api/instagram/webhook - Receives real DMs"
echo "  • GET /docs - Interactive API documentation"
echo ""
echo "Everything is working! Check:"
echo "  Dashboard: https://railway.app"
echo "  Logs: Real-time message processing"
echo "  Database: DMs saved automatically"
echo ""
