services:
  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: influence
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: influenceconnect
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./apps/api/db/init.sql:/docker-entrypoint-initdb.d/01-init.sql
    ports:
      - "5432:5432"

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://influence:${POSTGRES_PASSWORD}@db:5432/influenceconnect
      REDIS_URL: redis://redis:6379
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      HITL_REQUIRED: "true"
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: ${API_URL}
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  postgres_data:
